{
 "title": "Vodafone Statistics",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "WAN Traffic",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vodafone_wan_down_bytes_total[$__range])",
     "legendFormat": "Down"
    },
    {
     "expr": "increase(vodafone_wan_up_bytes_total[$__range])",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "WAN (5m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(vodafone_wan_down_bytes_total[$__rate_interval])",
     "legendFormat": "Down"
    },
    {
     "expr": "increase(vodafone_wan_up_bytes_total[$__rate_interval])",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "LAN (5m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(vodafone_lan1_down_bytes_total[5m])",
     "legendFormat": "LAN 1 Down"
    },
    {
     "expr": "increase(vodafone_lan1_up_bytes_total[5m])",
     "legendFormat": "LAN 1 Up"
    },
    {
     "expr": "increase(vodafone_lan2_down_bytes_total[5m])",
     "legendFormat": "Lan 2 Down"
    },
    {
     "expr": "increase(vodafone_lan2_up_bytes_total[5m])",
     "legendFormat": "LAN 2 Up"
    },
    {
     "expr": "(increase(vodafone_wifi_5ghz_down_bytes_total[5m]) + increase(vodafone_wifi_2_4ghz_down_bytes_total[5m]))",
     "legendFormat": "Wifi Down"
    },
    {
     "expr": "(increase(vodafone_wifi_5ghz_up_bytes_total[5m]) + increase(vodafone_wifi_2_4ghz_up_bytes_total[5m]))",
     "legendFormat": "Wifi Up"
    },
    {
     "expr": "increase(vodafone_lan4_down_bytes_total[5m])",
     "legendFormat": "Lan 4 Down"
    },
    {
     "expr": "increase(vodafone_lan4_up_bytes_total[5m])",
     "legendFormat": "LAN 4 Up"
    }
   ]
  },
  {
   "title": "LAN1",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vodafone_lan1_down_bytes_total[$__range])",
     "legendFormat": "Down"
    },
    {
     "expr": "increase(vodafone_lan1_up_bytes_total[$__range])",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "LAN 2",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vodafone_lan2_down_bytes_total[$__range])",
     "legendFormat": "Down"
    },
    {
     "expr": "increase(vodafone_lan2_up_bytes_total[$__range])",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Wifi",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vodafone_wifi_5ghz_down_bytes_total[$__range]) + increase(vodafone_wifi_2_4ghz_down_bytes_total[$__range])",
     "legendFormat": "Down"
    },
    {
     "expr": "increase(vodafone_wifi_5ghz_up_bytes_total[$__range]) + increase(vodafone_wifi_2_4ghz_up_bytes_total[$__range])",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "Wifi 2.4 GHz and 5GHz",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vodafone_wifi_2_4ghz_up_bytes_total[$__range]) + increase(vodafone_wifi_2_4ghz_down_bytes_total[$__range])",
     "legendFormat": "2.4 GHz"
    },
    {
     "expr": "increase(vodafone_wifi_5ghz_up_bytes_total[$__range]) + increase(vodafone_wifi_5ghz_down_bytes_total[$__range])",
     "legendFormat": "5 GHz"
    }
   ]
  },
  {
   "title": "LAN 3",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vodafone_lan3_down_bytes_total[$__range])",
     "legendFormat": "Down"
    },
    {
     "expr": "increase(vodafone_lan3_up_bytes_total[$__range])",
     "legendFormat": "Up"
    }
   ]
  },
  {
   "title": "LAN4",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vodafone_lan4_down_bytes_total[$__range])",
     "legendFormat": "Down"
    },
    {
     "expr": "increase(vodafone_lan4_up_bytes_total[$__range])",
     "legendFormat": "Up"
    }
   ]
  }
 ]
}